set-option -g @theme_symbol_ab         ""
set-option -g @theme_symbol_bc         ""
set-option -g @theme_symbol_cc         ""
set-option -g @theme_symbol_xx         ""
set-option -g @theme_symbol_xy         ""
set-option -g @theme_symbol_yz         ""
set-option -g @theme_symbol_cwin_left  ""
set-option -g @theme_symbol_cwin_right ""
set-option -g @theme_symbol_win_left   " "
set-option -g @theme_symbol_win_right  " "
