set-option -g @theme_symbol_ab         stair-down
set-option -g @theme_symbol_bc         stair-down
set-option -g @theme_symbol_cc         stair-down
set-option -g @theme_symbol_xx         stair-up
set-option -g @theme_symbol_xy         stair-up
set-option -g @theme_symbol_yz         stair-up
set-option -g @theme_symbol_cwin_left  stair-up
set-option -g @theme_symbol_cwin_right stair-down
set-option -g @theme_symbol_win_left   stair-up
set-option -g @theme_symbol_win_right  stair-down
