theme = "everforest_dark"

[editor]
line-number = "relative"
mouse = false
gutters = ["diagnostics", "line-numbers", "diff", "spacer"]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
C-s = ["normal_mode", ":write", "insert_mode"]

[keys.normal]
C-s = ":write"
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
w = ":write"
q = ":quit"
"," = ":config-open"
"|" = ":vsplit"
"\\" = ":vsplit"
minus = ":hsplit"
