#: Window status current {{{
set-option -wg  @active_window_status_fg_computed "#{s|\n*([^\n]+).*|\\1|r;s|\n*||r:"
set-option -wga @active_window_status_fg_computed   "\n#{?window_marked_flag,#{T:@marked_active_window_status_fg},}"
set-option -wga @active_window_status_fg_computed   "\n#{?window_marked_flag,#{T:@marked_window_status_fg},}"
set-option -wga @active_window_status_fg_computed   "\n#{T:@active_window_status_fg}"
set-option -wga @active_window_status_fg_computed   "\n#{T:@window_status_fg}"
set-option -wga @active_window_status_fg_computed "}"
set-option -wg  @active_window_status_bg_computed "#{s|\n*([^\n]+).*|\\1|r;s|\n*||r:"
set-option -wga @active_window_status_bg_computed   "\n#{?window_marked_flag,#{T:@marked_active_window_status_bg},}"
set-option -wga @active_window_status_bg_computed   "\n#{?window_marked_flag,#{T:@marked_window_status_bg},}"
set-option -wga @active_window_status_bg_computed   "\n#{T:@active_window_status_bg}"
set-option -wga @active_window_status_bg_computed   "\n#{T:@window_status_bg}"
set-option -wga @active_window_status_bg_computed "}"
set-option -wg  @active_window_status_left_symbol_resolved "#{s|\n*([^\n]+).*|\\1|r;s|\n*||r:"
set-option -wga @active_window_status_left_symbol_resolved   "\n#{T:@active_window_status_left_symbol}"
set-option -wga @active_window_status_left_symbol_resolved   "\n#{T:@symbol_rtl}"
set-option -wga @active_window_status_left_symbol_resolved "}"
set-option -wg  @active_window_status_right_symbol_resolved "#{s|\n*([^\n]+).*|\\1|r;s|\n*||r:"
set-option -wga @active_window_status_right_symbol_resolved   "\n#{T:@active_window_status_right_symbol}"
set-option -wga @active_window_status_right_symbol_resolved   "\n#{T:@symbol_ltr}"
set-option -wga @active_window_status_right_symbol_resolved "}"
set-option -wg  @active_window_status_left_symbol_rendered "#{?#{m|r:&#{T:@active_window_status_left_symbol_resolved}\s*=,#{T:@symbols}},"
set-option -wga @active_window_status_left_symbol_rendered   "#{"
set-option -wga @active_window_status_left_symbol_rendered     "s|.*&#{T:@active_window_status_left_symbol_resolved}\s*=\s*([^\s]).*|\\1|;"
set-option -wga @active_window_status_left_symbol_rendered     ":@symbols"
set-option -wga @active_window_status_left_symbol_rendered   "},"
set-option -wga @active_window_status_left_symbol_rendered   "#{T:@active_window_status_left_symbol_resolved}"
set-option -wga @active_window_status_left_symbol_rendered "}"
set-option -wg  @active_window_status_right_symbol_rendered "#{?#{m|r:&#{T:@active_window_status_right_symbol_resolved}\s*=,#{T:@symbols}},"
set-option -wga @active_window_status_right_symbol_rendered   "#{"
set-option -wga @active_window_status_right_symbol_rendered     "s|.*&#{T:@active_window_status_right_symbol_resolved}\s*=\s*([^\s]).*|\\1|;"
set-option -wga @active_window_status_right_symbol_rendered     ":@symbols"
set-option -wga @active_window_status_right_symbol_rendered   "},"
set-option -wga @active_window_status_right_symbol_rendered   "#{T:@active_window_status_right_symbol_resolved}"
set-option -wga @active_window_status_right_symbol_rendered "}"
set-option -wg  @active_window_status_left_style   "#{?"
set-option -wga @active_window_status_left_style     "#{&&:"
set-option -wga @active_window_status_left_style       "#{T:@active_window_status_bg_computed},"
set-option -wga @active_window_status_left_style       "#{!=:#{T:@active_window_status_bg_computed},#{T:@status_bg}}"
set-option -wga @active_window_status_left_style     "},"
set-option -wga @active_window_status_left_style     "#[nobold nounderscore noitalics"
set-option -wga @active_window_status_left_style     " #{s|^[^\S]+\\|[^\S]+$||g;s|.+|fg=\\0|:#{T:@active_window_status_bg_computed}}"
set-option -wga @active_window_status_left_style     "],"
set-option -wga @active_window_status_left_style     "#[nobold nounderscore noitalics"
set-option -wga @active_window_status_left_style     " #{s|^[^\S]+\\|[^\S]+$||g;s|.+|fg=\\0|:#{?@active_window_status_symbol_fg,#{T:@active_window_status_symbol_fg},#{T:@active_window_status_fg_computed}}}"
set-option -wga @active_window_status_left_style     "]"
set-option -wga @active_window_status_left_style   "}#[push-default]"
set-option -wg  @active_window_status_right_style  "#[default]"
set-option -wg  @active_window_status_center_style "#["
set-option -wga @active_window_status_center_style " #{s|^[^\S]+\\|[^\S]+$||g;s|.+|fg=\\0|:#{T:@active_window_status_fg_computed}}"
set-option -wga @active_window_status_center_style " #{s|^[^\S]+\\|[^\S]+$||g;s|.+|bg=\\0|:#{T:@active_window_status_bg_computed}}"
set-option -wga @active_window_status_center_style "]"
set-option -wg  window-status-current-format ""
set-option -wga window-status-current-format "#{T:@active_window_status_left_style}"
set-option -wga window-status-current-format "#{T:@active_window_status_left_symbol_rendered}"
set-option -wga window-status-current-format "#{T:@active_window_status_center_style}"
set-option -wga window-status-current-format " "
set-option -wga window-status-current-format "#{T:@window_index_fwid}."
set-option -wga window-status-current-format " "
set-option -wga window-status-current-format "#{s|\n*([^\n]+).*|\\1|r;s|\n*||r:"
set-option -wga window-status-current-format   "\n#{window_name}"
set-option -wga window-status-current-format   "\n#{T:@pane_current_path_styled}"
set-option -wga window-status-current-format "}"
set-option -wga window-status-current-format "#{T:@window_zoomed_icon}"
set-option -wga window-status-current-format " "
set-option -wga window-status-current-format "#{T:@active_window_status_right_style}"
set-option -wga window-status-current-format "#{T:@active_window_status_right_symbol_rendered}"
#: }}}
