#: Pane border {{{
set-option -g   @pane_status_left_symbol_resolved "#{s|\n*([^\n]+).*|\\1|r;s|\n*||r:"
set-option -ga  @pane_status_left_symbol_resolved   "\n#{T:@pane_status_left_symbol}"
set-option -ga  @pane_status_left_symbol_resolved   "\n#{T:@symbol_rtl_sep}"
set-option -ga  @pane_status_left_symbol_resolved "}"
set-option -g   @pane_status_right_symbol_resolved "#{s|\n*([^\n]+).*|\\1|r;s|\n*||r:"
set-option -ga  @pane_status_right_symbol_resolved   "\n#{T:@pane_status_right_symbol}"
set-option -ga  @pane_status_right_symbol_resolved   "\n#{T:@symbol_ltr_sep}"
set-option -ga  @pane_status_right_symbol_resolved "}"
set-option -g   @pane_status_left_symbol_rendered "#{?#{m|r:&#{T:@pane_status_left_symbol_resolved}\s*=,#{T:@symbols}},"
set-option -ga  @pane_status_left_symbol_rendered   "#{"
set-option -ga  @pane_status_left_symbol_rendered     "s|.*&#{T:@pane_status_left_symbol_resolved}\s*=\s*([^\s]).*|\\1|;"
set-option -ga  @pane_status_left_symbol_rendered     ":@symbols"
set-option -ga  @pane_status_left_symbol_rendered   "},"
set-option -ga  @pane_status_left_symbol_rendered   "#{T:@pane_status_left_symbol_resolved}"
set-option -ga  @pane_status_left_symbol_rendered "}"
set-option -g   @pane_status_right_symbol_rendered "#{?#{m|r:&#{T:@pane_status_right_symbol_resolved}\s*=,#{T:@symbols}},"
set-option -ga  @pane_status_right_symbol_rendered   "#{"
set-option -ga  @pane_status_right_symbol_rendered     "s|.*&#{T:@pane_status_right_symbol_resolved}\s*=\s*([^\s]).*|\\1|;"
set-option -ga  @pane_status_right_symbol_rendered     ":@symbols"
set-option -ga  @pane_status_right_symbol_rendered   "},"
set-option -ga  @pane_status_right_symbol_rendered   "#{T:@pane_status_right_symbol_resolved}"
set-option -ga  @pane_status_right_symbol_rendered "}"
set-option -g   @active_pane_status_left_symbol_resolved "#{s|\n*([^\n]+).*|\\1|r;s|\n*||r:"
set-option -ga  @active_pane_status_left_symbol_resolved   "\n#{T:@active_pane_status_left_symbol}"
set-option -ga  @active_pane_status_left_symbol_resolved   "\n#{T:@pane_status_left_symbol}"
set-option -ga  @active_pane_status_left_symbol_resolved   "\n#{T:@symbol_rtl_sep}"
set-option -ga  @active_pane_status_left_symbol_resolved "}"
set-option -g   @active_pane_status_right_symbol_resolved "#{s|\n*([^\n]+).*|\\1|r;s|\n*||r:"
set-option -ga  @active_pane_status_right_symbol_resolved   "\n#{T:@active_pane_status_right_symbol}"
set-option -ga  @active_pane_status_right_symbol_resolved   "\n#{T:@pane_status_right_symbol}"
set-option -ga  @active_pane_status_right_symbol_resolved   "\n#{T:@symbol_ltr_sep}"
set-option -ga  @active_pane_status_right_symbol_resolved "}"
set-option -g   @active_pane_status_left_symbol_rendered "#{?#{m|r:&#{T:@active_pane_status_left_symbol_resolved}\s*=,#{T:@symbols}},"
set-option -ga  @active_pane_status_left_symbol_rendered   "#{"
set-option -ga  @active_pane_status_left_symbol_rendered     "s|.*&#{T:@active_pane_status_left_symbol_resolved}\s*=\s*([^\s]).*|\\1|;"
set-option -ga  @active_pane_status_left_symbol_rendered     ":@symbols"
set-option -ga  @active_pane_status_left_symbol_rendered   "},"
set-option -ga  @active_pane_status_left_symbol_rendered   "#{T:@active_pane_status_left_symbol_resolved}"
set-option -ga  @active_pane_status_left_symbol_rendered "}"
set-option -g   @active_pane_status_right_symbol_rendered "#{?#{m|r:&#{T:@active_pane_status_right_symbol_resolved}\s*=,#{T:@symbols}},"
set-option -ga  @active_pane_status_right_symbol_rendered   "#{"
set-option -ga  @active_pane_status_right_symbol_rendered     "s|.*&#{T:@active_pane_status_right_symbol_resolved}\s*=\s*([^\s]).*|\\1|;"
set-option -ga  @active_pane_status_right_symbol_rendered     ":@symbols"
set-option -ga  @active_pane_status_right_symbol_rendered   "},"
set-option -ga  @active_pane_status_right_symbol_rendered   "#{T:@active_pane_status_right_symbol_resolved}"
set-option -ga  @active_pane_status_right_symbol_rendered "}"
set-option -g   @pane_status_left_style   "#[nobold nounderscore noitalics"
set-option -ga  @pane_status_left_style   " #{s|^[^\S]+\\|[^\S]+$||g;s|.+|fg=\\0|:#{T:@pane_status_bg}}"
set-option -ga  @pane_status_left_style   "]#[push-default]"
set-option -g   @pane_status_right_style  "#[default]"
set-option -g   @pane_status_center_style "#["
set-option -ga  @pane_status_center_style " #{s|^[^\S]+\\|[^\S]+$||g;s|.+|fg=\\0|:#{T:@pane_status_fg}}"
set-option -ga  @pane_status_center_style " #{s|^[^\S]+\\|[^\S]+$||g;s|.+|bg=\\0|:#{T:@pane_status_bg}}"
set-option -ga  @pane_status_center_style "]"
set-option -g   @active_pane_status_left_style   "#[nobold nounderscore noitalics"
set-option -ga  @active_pane_status_left_style   " #{s|^[^\S]+\\|[^\S]+$||g;s|.+|fg=\\0|:#{T:@active_pane_status_bg}}"
set-option -ga  @active_pane_status_left_style   "]"
set-option -g   @active_pane_status_right_style  "#[default]"
set-option -g   @active_pane_status_center_style "#["
set-option -ga  @active_pane_status_center_style " #{s|^[^\S]+\\|[^\S]+$||g;s|.+|fg=\\0|:#{T:@active_pane_status_fg}}"
set-option -ga  @active_pane_status_center_style " #{s|^[^\S]+\\|[^\S]+$||g;s|.+|bg=\\0|:#{T:@active_pane_status_bg}}"
set-option -ga  @active_pane_status_center_style "]"
set-option -g   @pane_status_content " "
set-option -ga  @pane_status_content "#{T:@pane_index_fwid}. "
set-option -ga  @pane_status_content "#{?@pane_title,"
set-option -ga  @pane_status_content   "＄ #{T:@pane_title},"
set-option -ga  @pane_status_content   "  #{T:@pane_current_path_styled}"
set-option -ga  @pane_status_content "}"
set-option -ga  @pane_status_content "#{T:@window_zoomed_icon}"
set-option -ga  @pane_status_content " "
set-option -g  pane-border-format ""
set-option -ga pane-border-format "#{?pane_active,"
set-option -ga pane-border-format   "#{T:@active_pane_status_left_style}"
set-option -ga pane-border-format   "#{T:@active_pane_status_left_symbol_rendered}"
set-option -ga pane-border-format   "#{T:@active_pane_status_center_style}"
set-option -ga pane-border-format   "#{T:@pane_status_content}"
set-option -ga pane-border-format   "#{T:@active_pane_status_right_style}"
set-option -ga pane-border-format   "#{T:@active_pane_status_right_symbol_rendered}"
set-option -ga pane-border-format   ","
set-option -ga pane-border-format   "#{T:@pane_status_left_style}"
set-option -ga pane-border-format   "#{T:@pane_status_left_symbol_rendered}"
set-option -ga pane-border-format   "#{T:@pane_status_center_style}"
set-option -ga pane-border-format   "#{T:@pane_status_content}"
set-option -ga pane-border-format   "#{T:@pane_status_right_style}"
set-option -ga pane-border-format   "#{T:@pane_status_right_symbol_rendered}"
set-option -ga pane-border-format "}"
#: }}}
